/*
 * Credits
 * The Credits API provides information about customer credit lines.
 *
 * OpenAPI spec version: 2.2.0
 * Contact: gipinacho@santander.com.mx
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.bancosantander.likeu.model;

import java.util.Objects;

/**
 * Retrieves the payment card basic information
 */
public class PaymentDetail {
	private Integer amountPayment = null;

	private Integer minimumAmount = null;

	private java.util.Date operationDate = null;

	/**
	 * Indicates the date on which the payment was made. [ISO 8601]
	 * (https://www.iso.org/iso-8601-date-and-time-format.html
	 * 
	 * @return operationDate
	 **/
	public java.util.Date getOperationDate() {
		return operationDate;
	}

	public void setOperationDate(java.util.Date operationDate) {
		this.operationDate = operationDate;
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append("class PaymentDetail {\n");

		sb.append("    amountPayment: ")
				.append(toIndentedString(amountPayment)).append("\n");
		sb.append("    minimumAmount: ")
				.append(toIndentedString(minimumAmount)).append("\n");
		sb.append("    operationDate: ")
				.append(toIndentedString(operationDate)).append("\n");
		sb.append("}");
		return sb.toString();
	}

	/**
	 * Convert the given object to string with each line indented by 4 spaces
	 * (except the first line).
	 */
	private String toIndentedString(java.lang.Object o) {
		if (o == null) {
			return "null";
		}
		return o.toString().replace("\n", "\n    ");
	}

	public java.lang.Integer getAmountPayment() {
		return this.amountPayment;
	}

	public void setAmountPayment(java.lang.Integer amountPayment) {
		this.amountPayment = amountPayment;
	}

	public java.lang.Integer getMinimumAmount() {
		return this.minimumAmount;
	}

	public void setMinimumAmount(java.lang.Integer minimumAmount) {
		this.minimumAmount = minimumAmount;
	}

	public PaymentDetail() {
	}

	public PaymentDetail(java.lang.Integer amountPayment,
			java.lang.Integer minimumAmount, java.util.Date operationDate) {
		this.amountPayment = amountPayment;
		this.minimumAmount = minimumAmount;
		this.operationDate = operationDate;
	}

}
